### ISSUE TITLE
Tests are regional language dependent

### ISSUE THREAD

**Issue by seanstory** [seanstory/workplace-search-java#3]
Originally reported by @sguerreropert here: https://github.com/seanstory/workplace-search-java/issues/1#issuecomment-685984642

```
`-------------------------------------------------------------------------------
Test set: com.sstory.workplace.search.sdk.api.YamlConfigTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.004 sec <<< FAILURE!
test yaml parsing(com.sstory.workplace.search.sdk.api.YamlConfigTest)  Time elapsed: 0.447 sec  <<< FAILURE!
Condition not satisfied:

exceptionMsg.contains(expectedErrMsg)
|            |        |
|            false    No such file or directory
src/test/resources/four.yml (No existe el fichero o el directorio)

        at com.sstory.workplace.search.sdk.api.YamlConfigTest.test yaml parsing(YamlConfigTest.groovy:22)
```

That test is expecting a FileNotFoundException with a message `No such file or directory`, but the actual error message is in another language.

**Comment by seanstory** [comment]
@sguerreropert can you take a look at the https://github.com/seanstory/workplace-search-java/tree/bugfix/3-do-not-assume-exception-message branch, and let me know if that resolves your build issue?

**Comment by sguerreropert** [comment]
> @sguerreropert can you take a look at the https://github.com/seanstory/workplace-search-java/tree/bugfix/3-do-not-assume-exception-message branch, and let me know if that resolves your build issue?

Thank you very much, it has resolved the issue.
